### ISSUE TITLE
Unable to run npm install

### ISSUE THREAD

**Issue by TonyGregg** [PeculiarVentures/pkcs11js#15]
npm ERR! Failed at the pkcs11js@1.0.9 install script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pkcs11js package,

95 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
696 error node v6.9.1
697 error npm  v3.10.8
698 error code ELIFECYCLE
699 error pkcs11js@1.0.9 install: `npm run build`
[npm-debug.zip](https://github.com/PeculiarVentures/pkcs11js/files/1151150/npm-debug.zip)

**Comment by rmhrisk** [comment]
@TonyGregg @microshine is on holiday and may not respond for a week or so. I don't have a Windows box handy to debug on this end. My best guess is you need to use a more recent npm.

**Comment by TonyGregg** [comment]
Thanks for responding.


I installed latest npm and I get the below errors now. Not sure what to do.
...

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli
'C:\\Users\\anton\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pkcs11js@1.0.9~prebuild: pkcs11js@1.0.9
6 info lifecycle pkcs11js@1.0.9~build: pkcs11js@1.0.9
7 verbose lifecycle pkcs11js@1.0.9~build: unsafe-perm in lifecycle true
8 verbose lifecycle pkcs11js@1.0.9~build: PATH:
C:\Users\anton\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\anton\go\src\fabric-samples\fabcar\node_modules\pkcs11js\node_modules\.bin;C:\Users\anton\go\src\fabric-samples\fabcar\node_modules\.bin;C:\Users\anton\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\anton\go\src\fabric-samples\fabcar\node_modules\pkcs11js\node_modules\.bin;C:\Users\anton\go\src\fabric-samples\fabcar\node_modules\.bin;C:\Users\anton\bin;C:\Program
Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program
Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program
Files\Git\mingw64\bin;C:\Program
Files\Git\usr\bin;C:\Users\anton\bin;C:\Python27;C:\Python27\Scripts;C:\Program
Files\Java\jdk1.8.0_101;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program
Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS
Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program
Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
Files\Java\jdk1.8.0_65\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program
Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
Files\nodejs;C:\Program Files
(x86)\Skype\Phone;C:\ProgramData\chocolatey\bin;C:\Program
Files\Git\cmd;C:\Go\bin;C:\Ruby22\bin;C:\Users\anton\AppData\Local\Microsoft\WindowsApps;C:\Users\anton\AppData\Roaming\npm;C:\Users\anton\bin\Sencha\Cmd\6.5.0.180;C:\Program
Files\Docker Toolbox;C:\Program
Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle pkcs11js@1.0.9~build: CWD:
C:\Users\anton\go\src\fabric-samples\fabcar\node_modules\pkcs11js
10 silly lifecycle pkcs11js@1.0.9~build: Args: [ '/d /s /c', 'node-gyp
configure build' ]
11 silly lifecycle pkcs11js@1.0.9~build: Returned: code: 1  signal: null
12 info lifecycle pkcs11js@1.0.9~build: Failed to exec build script
13 verbose stack Error: pkcs11js@1.0.9 build: `node-gyp configure build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous>
(C:\Users\anton\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous>
(C:\Users\anton\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:226:5)
14 verbose pkgid pkcs11js@1.0.9
15 verbose cwd C:\Users\anton\go\src\fabric-samples\fabcar\node_modules\pkcs11js
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe"
"C:\\Users\\anton\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
"run" "build"
18 verbose node v6.9.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error pkcs11js@1.0.9 build: `node-gyp configure build`
22 error Exit status 1
23 error Failed at the pkcs11js@1.0.9 build script.
23 error This is probably not a problem with npm. There is likely
additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rmhrisk** [comment]
We will have to wait for @microshine

**Comment by kcCoding** [comment]
Try installing openSSL as described at: https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide#openssl
that worked for me

**Comment by rmhrisk** [comment]
@TonyGregg, did that work for you?

**Comment by microshine** [comment]
@TonyGregg I tried to install `pkcs11js` on my Windows machine. It works for me.
`pkcs11js` doens't use OpenSSL.

Could you try to build `pkcs11js` manually?

```
git clone https://github.com/PeculiarVentures/pkcs11js.git --depth 1
cd pkcs11js
npm install
```

**Comment by TonyGregg** [comment]
Hello @microshine 

Thanks for responding. I tried pcks11js manually with the commands you gave, but it failed. Following is the error

C:\Users\anton\go\src\pkcs11js>if not defined npm_config_node_gyp (node "C:\Users\anton\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\anton\go\src\pkcs11js\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\anton\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\anton\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\anton\go\src\pkcs11js
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.0.9 build: `node-gyp configure build`
npm ERR! Exit status 1

**Comment by TonyGregg** [comment]
I am using windows 10. Not sure if I am missing some .NET framework.

**Comment by microshine** [comment]
What version of Visual Studio do you use?

**Comment by TonyGregg** [comment]
I do not have Microsoft Visual Studio. I have Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215. Do I need to install Visual Studio?

**Comment by TonyGregg** [comment]
I have installed .NET framework SDK 4.7, still the error is same.

**Comment by TonyGregg** [comment]
I have also installed Visual Studio Professional 2017 and tried, ended with same error. 


MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\anton\go\src\pkcs11js\build\binding.sln]

**Comment by microshine** [comment]
Could you try to open `C:\Users\anton\go\src\pkcs11js\build\binding.sln` and build it from VS?

**Comment by TonyGregg** [comment]
It worked. Thank you very much @microshine !!

**Comment by zamrokk** [comment]
Hi all,
I have exactly the same error on my Mac.
I did the previous commands to build it separately and still same problem

```
git clone https://github.com/PeculiarVentures/pkcs11js.git --depth 1
cd pkcs11js
npm install
```

node -v
v8.4.0

npm -v
5.4.1



```
13885 info lifecycle pkcs11js@1.0.9~install: pkcs11js@1.0.9
13886 verbose lifecycle pkcs11js@1.0.9~install: unsafe-perm in lifecycle true
13887 verbose lifecycle pkcs11js@1.0.9~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/benjaminfuentes/Desktop/fabric-samples/fabcar/pkcs11js/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/android-sdk-macosx/tools:/usr/local/android-sdk-macosx/platform-tools:/usr/local/apache-maven-3.3.9/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home:/opt/IBM/db2/V10.1/include/lib64:/usr/lib/mongodb/bin:/usr/lib/gradle-2.14.1/bin:/usr/lib/protoc-3.0.0-osx-x86_64/bin:/usr/local/bin
13888 verbose lifecycle pkcs11js@1.0.9~install: CWD: /Users/benjaminfuentes/Desktop/fabric-samples/fabcar/pkcs11js
13889 silly lifecycle pkcs11js@1.0.9~install: Args: [ '-c', 'npm run build' ]
13890 silly lifecycle pkcs11js@1.0.9~install: Returned: code: 1  signal: null
13891 info lifecycle pkcs11js@1.0.9~install: Failed to exec install script
13892 verbose stack Error: pkcs11js@1.0.9 install: `npm run build`
13892 verbose stack Exit status 1
13892 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13892 verbose stack     at emitTwo (events.js:125:13)
13892 verbose stack     at EventEmitter.emit (events.js:213:7)
13892 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13892 verbose stack     at emitTwo (events.js:125:13)
13892 verbose stack     at ChildProcess.emit (events.js:213:7)
13892 verbose stack     at maybeClose (internal/child_process.js:927:16)
13892 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13893 verbose pkgid pkcs11js@1.0.9
13894 verbose cwd /Users/benjaminfuentes/Desktop/fabric-samples/fabcar/pkcs11js
13895 verbose Darwin 16.7.0
13896 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
13897 verbose node v8.4.0
13898 verbose npm  v5.4.1
13899 error code ELIFECYCLE
13900 error errno 1
13901 error pkcs11js@1.0.9 install: `npm run build`
13901 error Exit status 1
13902 error Failed at the pkcs11js@1.0.9 install script.
13902 error This is probably not a problem with npm. There is likely additional logging output above.
13903 verbose exit [ 1, true ]
```

**Comment by microshine** [comment]
@zamrokk Could you send log for next command?
```
cd pkcs11js
node-gyp configure build
```

**Comment by zamrokk** [comment]
build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/benjaminfuentes/Desktop/fabric-samples/fabcar/pkcs11js
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by microshine** [comment]
@zamrokk  I cannot reproduce this error on my Mac.
Could you try to build it from Xcode?

```
node-gyp configure -- -f xcode
open build/binding.xcodeproj
```

**Comment by zamrokk** [comment]
build success

![image](https://user-images.githubusercontent.com/2536368/30904103-330dd140-a371-11e7-9345-39106ef82c34.png)

**Comment by zamrokk** [comment]
node-gyp configure build     is ok now

![image](https://user-images.githubusercontent.com/2536368/30904151-627dea64-a371-11e7-843d-848d011fca68.png)

**Comment by zamrokk** [comment]
npm i   is passing also

![image](https://user-images.githubusercontent.com/2536368/30904190-8d80e004-a371-11e7-98f5-2b98290cb9c1.png)

**Comment by microshine** [comment]
@zamrokk Was there Xcode license agreement?

**Comment by zamrokk** [comment]
when i opened Xcode it did a small update. Maybe it is linked to that ? :/

**Comment by zamrokk** [comment]
now when i run  " npm i " on my initial project that uses pkcs11 as a dependency , it is ok

![image](https://user-images.githubusercontent.com/2536368/30904333-ffff601a-a371-11e7-9b3b-8d581cb07597.png)

**Comment by zamrokk** [comment]
thanks @microshine    ;o)

**Comment by microshine** [comment]
thanks @zamrokk too :)

**Comment by LacikIgor** [comment]
use python 2.7. if u have a python 3.x (the error logs are long enough for u to first google to this link and only than actually check logs)

**Comment by rmhrisk** [comment]
@lackigor without more information we can not help you. Sounds like your issue is independent of the one discussed in this bug. Please file a new bug.

**Comment by LacikIgor** [comment]
@rmhrisk Actually I do not have any issue (just wanted to help future visitors)
