### ISSUE TITLE
Cannot do npm install on Mac

### ISSUE THREAD

**Issue by BYuenPwC** [PeculiarVentures/pkcs11js#16]
Hi, having trouble doing npm install. 

Please can you help? Thanks!

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pkcs11js@1.0.9~prebuild: pkcs11js@1.0.9
6 info lifecycle pkcs11js@1.0.9~build: pkcs11js@1.0.9
7 verbose lifecycle pkcs11js@1.0.9~build: unsafe-perm in lifecycle true
8 verbose lifecycle pkcs11js@1.0.9~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/projectpath/node_modules/pkcs11js/node_modules/.bin:/Users/projectpath$
9 verbose lifecycle pkcs11js@1.0.9~build: CWD: /Users/projectpath/node_modules/pkcs11js
10 silly lifecycle pkcs11js@1.0.9~build: Args: [ '-c', 'node-gyp configure build' ]
11 silly lifecycle pkcs11js@1.0.9~build: Returned: code: 1  signal: null
12 info lifecycle pkcs11js@1.0.9~build: Failed to exec build script
13 verbose stack Error: pkcs11js@1.0.9 build: `node-gyp configure build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid pkcs11js@1.0.9
15 verbose cwd /Users/projectpath/node_modules/pkcs11js
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error pkcs11js@1.0.9 build: `node-gyp configure build`
22 error Exit status 1
23 error Failed at the pkcs11js@1.0.9 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rmhrisk** [comment]
@BYuenPwC works for me, just tried.

Must be environmental.

```
ryans-mbp:~ rmh$ cd /tmp
ryans-mbp:tmp rmh$ npm install pkcs11js

> pkcs11js@1.0.9 install /private/tmp/node_modules/pkcs11js
> npm run build


> pkcs11js@1.0.9 build /private/tmp/node_modules/pkcs11js
> node-gyp configure build
...
...
...
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ pkcs11js@1.0.9
added 3 packages in 16.611s
```

@microshine any ideas what it may be?

**Comment by BYuenPwC** [comment]
@rmhrisk , Thanks for your response. 

What version of node / npm  were you using?

**Comment by microshine** [comment]
@BYuenPwC I updated my NodeJS version to 8.4.0 and npm to 5.3.0. And module installation is ok for macOS Sierra 10.12.6

Could you try to build pkcs11js manually

```
git clone https://github.com/PeculiarVentures/pkcs11js.git --depth 1
cd pkcs11js
npm intsall
```
after dependency installetion
```
node-gyp configure
node-gyp build
```

This must help to show more details for module building error

**Comment by BYuenPwC** [comment]
Hi, 

I have managed to install it with just npm again. very strange. Thanks for your responses.

**Comment by recurrence** [comment]
Update NPM to 5.4.2
