### ISSUE TITLE
Unable to run - npm install pkcs11js

### ISSUE THREAD

**Issue by shuchivt** [PeculiarVentures/pkcs11js#19]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\shutripathy\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shutripathy\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\shutripathy\pkcs11js\node_modules\pkcs11js
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pkcs11js@1.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by microshine** [comment]
Could you try steps from this [issue](https://github.com/PeculiarVentures/pkcs11js/issues/15)?

**Comment by shuchivt** [comment]
Thank you this worked. how to integrate the nodejs program to read keys from aws cloudhsm

**Comment by shuchivt** [comment]
how should the following statement change if softhsm is installed on windows 10
pkcs11.load("/usr/local/lib/softhsm/libsofthsm2.so");

**Comment by rmhrisk** [comment]
I think you need token label also, @microshine

**Comment by shuchivt** [comment]
Thanks. kindly provide some more details

**Comment by microshine** [comment]
You can use [index.d.ts](https://github.com/PeculiarVentures/pkcs11js/blob/master/index.d.ts)  for API understanding

#### Example load()
[load](https://github.com/PeculiarVentures/pkcs11js/blob/master/index.d.ts#L147)

**Comment by krishnarajreal** [comment]
Navigate to node_module  and type the command below
"git clone https://github.com/PeculiarVentures/pkcs11js.git --depth 1"
and go to node_modules/pkcs11js and delete git folder
Now run "npm install"
