### ISSUE TITLE
Can this library support EFTPOS HSM?

### ISSUE THREAD

**Issue by kahwooi** [PeculiarVentures/pkcs11js#22]
Can this library support SafeNet Payment HSM?
I need to use DUKPT and PIN module.

**Comment by microshine** [comment]
If SafeNet Payment HSM has PKCS#11 library it must work with pkcs11js

```js
var pkcs11js = require("pkcs11js");

var pkcs11 = new pkcs11js.PKCS11();
pkcs11.load("/path/to/eftpos/hsm/pkcs11.so");

pkcs11.C_Initialize();

try {
    // Getting info about PKCS11 Module
    var module_info = pkcs11.C_GetInfo();

    console.log(module_info);
}
catch(e){
    console.error(e);
}

pkcs11.C_Finalize();
```

**Comment by microshine** [comment]
@kahwooi Have you applied pkcs11js to your HSM?

**Comment by singhmanpreet294** [comment]
@kahwooi  SafeNet Payment HSM already support DUKPUT through its dedicated APIs(Not PKCS APIs). You can call these API over a TCP/IP socket and perform required tasks as per your requirement.
