### ISSUE TITLE
How pkcs11js handle Vendor specific attributes?

### ISSUE THREAD

**Issue by mckenm** [PeculiarVentures/pkcs11js#28]
Hello,  I have a project that using attributes that are vendor attributes that start 0x40000000.  I wonder how will it translate or convert values from JS layer to API.  Like number to number/ string of number to number.  Is there a way I can specific or understand how it works?

**Comment by microshine** [comment]
You can use TypeScript Declaration file [index.d.ts](https://github.com/PeculiarVentures/pkcs11js/blob/master/index.d.ts) for best JS API understanding.

Attribute type is number
```ts
type Template = Attribute[];

interface Attribute {
    type: number;
    value?: number | boolean | string | Buffer;
}
```

You can use your own vendor values

```js
const CKA_MY_ATTRIBUTE_1 = pkcs11js.CKA_VENDOR_DEFINED | 0x00000001;
// or
const CKA_MY_ATTRIBUTE_2 = 0x40000002;

const attrs = pkcs11.C_GetAttributeValue(session, object, [{ type: CKA_MY_ATTRIBUTE_1 }]);
console.log(attrs[0].value); // Buffer
```
