### ISSUE TITLE
centos error

### ISSUE THREAD

**Issue by gantleman** [PeculiarVentures/pkcs11js#31]
[root@localhost nodeTest]# npm install pkcs11js
npm WARN package.json nodeTest@1.0.0 No repository field.
npm WARN package.json nodeTest@1.0.0 No README data
\
> pkcs11js@1.0.15 install /root/nodeTest/node_modules/pkcs11js
> node-gyp rebuild

make: Entering directory `/root/nodeTest/node_modules/pkcs11js/build'
  CXX(target) Release/obj.target/pkcs11/src/main.o
In file included from ../src/pkcs11/error.h:6:0,
                 from ../src/pkcs11/v8_convert.h:13,
                 from ../src/pkcs11/param.h:5,
                 from ../src/const.h:17,
                 from ../src/main.cpp:4:
../src/pkcs11/scope.h:7:1: error: expected unqualified-id before ‘using’
 using Scoped = std::shared_ptr<T>;
 ^
In file included from ../src/pkcs11/v8_convert.h:13:0,
                 from ../src/pkcs11/param.h:5,
                 from ../src/const.h:17,
                 from ../src/main.cpp:4:
../src/pkcs11/error.h:12:2: error: ‘Scoped’ does not name a type
  Scoped<Error> stack;
[root@localhost nodeTest]# npm install pkcs11js
npm WARN package.json nodeTest@1.0.0 No repository field.
npm WARN package.json nodeTest@1.0.0 No README data
\
> pkcs11js@1.0.15 install /root/nodeTest/node_modules/pkcs11js
> node-gyp rebuild

make: Entering directory `/root/nodeTest/node_modules/pkcs11js/build'
  CXX(target) Release/obj.target/pkcs11/src/main.o
In file included from ../src/pkcs11/error.h:6:0,
                 from ../src/pkcs11/v8_convert.h:13,
                 from ../src/pkcs11/param.h:5,
                 from ../src/const.h:17,
                 from ../src/main.cpp:4:
../src/pkcs11/scope.h:7:1: error: expected unqualified-id before ‘using’
 using Scoped = std::shared_ptr<T>;
 ^
In file included from ../src/pkcs11/v8_convert.h:13:0,
                 from ../src/pkcs11/param.h:5,
                 from ../src/const.h:17,
                 from ../src/main.cpp:4:
../src/pkcs11/error.h:12:2: error: ‘Scoped’ does not name a type
  Scoped<Error> stack;

**Comment by microshine** [comment]
Please try the latest version of `pkcs11js`. Do you still have got the same error?
I'm going to close that issue. I'll reopen it if the problem is not fixed
