### ISSUE TITLE
Templete Incomplete when when creating data object

### ISSUE THREAD

**Issue by rafal-ics** [PeculiarVentures/pkcs11js#35]
I trying example in the read me to Create Object with Yubikey 4.

I get Error: CKR_TEMPLATE_INCOMPLETE:208

when calling: 

var nObject = pkcs11.C_CreateObject(session, [
        { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_DATA },
        { type: pkcs11js.CKA_TOKEN, value: false },
        { type: pkcs11js.CKA_PRIVATE, value: false },
        { type: pkcs11js.CKA_LABEL, value: "My Label" },
    ]);

Any suggestions please?

**Comment by rmhrisk** [comment]
You will have to turn on logging in the PKCS11 library and see if it tells you why it wants more data in the template

Each library has its own requirements that are normally not documented.

**Comment by microshine** [comment]
Yubico PKCS11 library doesn't support `CKO_DATA` for `C_CreateObject` function

https://github.com/Yubico/yubico-piv-tool/blob/master/ykcs11/ykcs11.c#L975-L992
