### ISSUE TITLE
AES_KEY_WRAP reporting CKR_MECHANISM_INVALID

### ISSUE THREAD

**Issue by jahluwalia** [PeculiarVentures/pkcs11js#36]
I'm using graphene to try to wrap an AES key stored in SoftHSM2. Here is the code:

```
mech = { name: 'AES_KEY_WRAP', params: new Buffer([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) }; 
wKey = _session.wrapKey(mech, wrappingKeyObj, keyObj); 
```

I get the following error:
`CKR_MECHANISM_INVALID:112\n    at Error (native) C_WrapKey:949`

I noticed the values for AES_KEY_WRAP are different in pkcs11js and SoftHSM2 as follows:

Pkcs11js:
`#define CKM_AES_KEY_WRAP               0x00001090`
 
SoftHSM2:
`#define CKM_AES_KEY_WRAP (0x2109UL)`

Is there a workaround for this? 

Thanks,
Jas

**Comment by jahluwalia** [comment]
Thank you for that. 

When i set the mechanism as follows, it works: 

`Mechanism = 'SOFTHSM_AES_KEY_WRAP';  // this one works`

However, if i try to pass an IV, as follows:

`Mechanism = { name: 'SOFTHSM_AES_KEY_WRAP', params: new Buffer([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) }; `

I get the following error:

`"CKR_ARGUMENTS_BAD:7    at Error (native) C_WrapKey:949"`

Any thoughts?

Thanks,
Jas

**Comment by rmhrisk** [comment]
That is the underlying implementation saying it doesnt like one or more of the arguments being passed.

Since softhsm is OSS you can look at its implementation to see why it throws this error.
