### ISSUE TITLE
Load method affects on the app performance.

### ISSUE THREAD

**Issue by minhnhatspk** [PeculiarVentures/pkcs11js#37]
As you guys can see on my issue title when I use the `load` method to load the library, It affects my app performance (Renderer process).
I'm using this module in my electron project. Let me show my problem details.
I have a screen to the user can insert their PIN.
After pressing the submit button, it redirects to the loading screen. In this screen, I have a loading animation. At the time the app calls the load method, the loading bar is hanged out for a while.

Could you guys help me to figure out this problem?

**Comment by rmhrisk** [comment]
The library you are calling via PKCS11js is blocking.

I do not know the architecture of your code but you need to move the PKCS11 call to someplace out of render path.

**Comment by rmhrisk** [comment]
Out of curiosity what kind of application have you made?
