### ISSUE TITLE
Type inconsistent error when trying to initialize GOST signing

### ISSUE THREAD

**Issue by LumaRay** [PeculiarVentures/pkcs11js#40]
I get a private key handle from Rutoken 2.0 ECP using your example:

```
var keys1 = {privateKey: null, publicKey: null};

pkcs11.C_FindObjectsInit(session, [
	{ type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PRIVATE_KEY },
	{ type: pkcs11js.CKA_LABEL, value: label }
]);
var hObject = pkcs11.C_FindObjects(session);
while (hObject) {
	var attrs = pkcs11.C_GetAttributeValue(session, hObject, [
		{ type: pkcs11js.CKA_CLASS },
		{ type: pkcs11js.CKA_TOKEN },
		{ type: pkcs11js.CKA_LABEL }
	]);

	keys1.privateKey = hObject;
	hObject = pkcs11.C_FindObjects(session);
}
pkcs11.C_FindObjectsFinal(session);
```
I check that keys1.privateKey has a non null value, then try to initialize signing algorithm:
```
pkcs11.C_SignInit(session, { mechanism: pkcs11js.CKM_GOSTR3410_WITH_GOSTR3411 }, keys1.privateKey);
```

But this returns an error:

```
Error: CKR_KEY_TYPE_INCONSISTENT:99
    at Error (native) crypto_init:563
```

**Comment by LumaRay** [comment]
Оказывается, Рутокен не поддерживает функции Update: https://dev.rutoken.ru/pages/viewpage.action?pageId=3178534

**Comment by LumaRay** [comment]
Finally worked this way:

```
pkcs11.C_SignInit(session, { mechanism: pkcs11js.CKM_GOSTR3410 }, keys1.privateKey);
var signature = Buffer.alloc(64);
signature = pkcs11.C_Sign(session, hash, signature);
```

**Comment by microshine** [comment]
Looks like `CKM_GOSTR3410` is a simple mechanism which is used for digest signing like CKM_RSA_PKCS. This is why it doesn't support `Update` functions.

**Comment by LumaRay** [comment]
Well, according to a comparison table from Rutoken documentation https://dev.rutoken.ru/pages/viewpage.action?pageId=3178538
rtPKCS11ECP + Рутокен ЭЦП (which I use) supports CKM_GOSTR3410_WITH_GOSTR3411 (for C_Sign) and extended CKM_GOSTR3410_WITH_GOSTR3411_12_256.

Moreover, it supports non-GOST cryptography: CKM_RSA_PKCS.

But still C_SignUpdate is not supported for any mechanism according to https://dev.rutoken.ru/pages/viewpage.action?pageId=3178534
