### ISSUE TITLE
How to add a function

### ISSUE THREAD

**Issue by LumaRay** [PeculiarVentures/pkcs11js#41]
Hello. I want to add an extended rutoken C_EX_PKCS7Sign function into your library https://dev.rutoken.ru/pages/viewpage.action?pageId=3178555#id-%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F-C_EX_PKCS7Sign()

How can I do this?

**Comment by microshine** [comment]
This is Rutoken specific function. It would be better to make fork `pkcs11-rutoken`

Steps to add custom PKCS#11 function

- Update PKCS11 headers by adding Rutoken Ex functions ([pkcs11f.h](https://github.com/PeculiarVentures/pkcs11js/blob/master/includes/pkcs11/pkcs11f.h))
- And types if needed ([pkcs11t.h](https://github.com/PeculiarVentures/pkcs11js/blob/master/includes/pkcs11/pkcs11t.h))
- Add function declaration and implementation to PKCS11 class ([pkcs11.h](https://github.com/PeculiarVentures/pkcs11js/blob/master/src/pkcs11/pkcs11.h), [pkcs11.cpp](https://github.com/PeculiarVentures/pkcs11js/blob/master/src/pkcs11/pkcs11.cpp))
- Wrap Ex functions to NodeJs objects (etc [C_SignInit](https://github.com/PeculiarVentures/pkcs11js/blob/master/src/node.cpp#L192))

More info and examples:
- [Nan](https://github.com/nodejs/nan)

**Comment by LumaRay** [comment]
Thanks, and after I alter those files, I need to recompile them? How?

**Comment by microshine** [comment]
```
node-gyp configure build
```

https://github.com/nodejs/node-gyp

If you are using Windows `node-gyp configure` must create VisualStudio Solution file and you can build/debug library from it

**Comment by LumaRay** [comment]
Thanks. I think changes are also needed in:
- node.h
- index.d.ts
