### ISSUE TITLE
pkijs vs pkcs11js use cases

### ISSUE THREAD

**Issue by muz3** [PeculiarVentures/pkcs11js#42]
Sorry, this question may not be posted in the correct channel. but I am trying to figure out when to use which library. It feels like to me pkcs11js is a subset of the pkijs. If I just want to work with softhsm, then pkcs11js is enough for me. thanks,

**Comment by rmhrisk** [comment]
@muz3 PKI.js provides support for all the various PKI related data structures such as X.509 certificates, CMS, etc.

pkcs11js is a binding for JS/TS applications to the PKCS#11 standard which was defined to enable a consistent API for callers to use smart cards and hardware security modules.

They are complementary and do very different things. Most applications that use pkcs11js also use PKI.js but not necessarily the other way around.

**Comment by rmhrisk** [comment]
I quickly looked at your cloned repositories, if your looking to interact with a hardware wallet for a cryptocurrency that exposes a PKCS#11 interface via its middleware you want pkcs11js.

If your implementing, for example, BIP 0070 you want PKIjs.

**Comment by muz3** [comment]
These are really helpful info. Thank you Ryan, and much appreciated.
