### ISSUE TITLE
CK_ULONG type attribute value in template can't be passed correctly on s390x

### ISSUE THREAD

**Issue by huxd-ibm** [PeculiarVentures/pkcs11js#43]
when invoking function that requires template, for example C_GenerateKeyPair, if we want to pass in some CK_ULONG type attribute in the template, for example CKA_KEY_TYPE, the value could not be passed correctly on s390x.

if we look at function `v2c_ATTRIBUTE` in file src/pkcs11/template.cpp, when `v8Value->IsNumber()` is true, if we try to print both value of "num" and value of  `*(CK_ULONG*)attr->pValue` using format `%lu`, we will see they actually have different value.
change the way to copy value of num to attr-pValue can fix the problem:
`*(CK_ULONG*)attr->pValue = num;`

**Comment by microshine** [comment]
I've published a new version `+ pkcs11js@1.0.18`. Can you try it?

**Comment by huxiangdong** [comment]
@microshine verified `pkcs11js@1.0.18`, it works! Thanks very much!

**Comment by huxd-ibm** [comment]
@microshine verified `pkcs11js@1.0.18` and it works! Thanks very much!
