### ISSUE TITLE
How get publicKeyId fom token?

### ISSUE THREAD

**Issue by ruslan-gennadievich** [PeculiarVentures/pkcs11js#45]
```

    const _pkcs11FindObjects = (pkcs11, pkcs11Session, pkcs11Template) => {
        pkcs11.C_FindObjectsInit(pkcs11Session, pkcs11Template);
        var objs = [];
        var obj = pkcs11.C_FindObjects(pkcs11Session);
        while (obj) {
            objs.push(obj);
            obj = pkcs11.C_FindObjects(pkcs11Session);
        }
        pkcs11.C_FindObjectsFinal(pkcs11Session);
        return objs;
    }    

    PrivKeysHandle = _pkcs11FindObjects(pkcs11, session, [
        { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PRIVATE_KEY },
        { type: pkcs11js.CKA_TOKEN, value: true },
        { type: pkcs11js.CKA_LABEL, value: "mylabel" },
    ])         
    
    // Get public_key_id...
    publicKeyId = pkcs11.C_GetAttributeValue(session, PrivKeysHandle[0], [{ type: 0x129 }])
    console.log('publicKey', publicKeyId[0].value.toString())


```
This not working
how i can get public key and pubKeyId from token ?
I have only private key on token

**Comment by rmhrisk** [comment]
This looks right to me, do you know the public key is on the token?

**Comment by ruslan-gennadievich** [comment]
No, i have only private key on token.
So, then make PublicKey from PrivateKey
How i can do this by pkcs11js ?

Thanks for help.

**Comment by rmhrisk** [comment]
Your above code is reading at attribute on a key and would only work if that attribute set on the key in advance.

It is possible to derive the public key from a private key with some algorithms, for example with RSA:

An RSA public key consists of two values:

- the modulus n (a product of two secretly chosen large primes p and q), 
- the public exponent e (which can be the same for many keys and is typically chosen to be a small odd prime, most commonly either 3 or 216+1 = 65537).

An RSA private key consists of two values:

- the modulus n (same as in the public key), and
- the private exponent d (calculated from the public exponent e and the factors p and q of the modulus).

It is possible that the format for storing the private key will retain other values such as the public exponent but I don’t think you can rely on that, especially across algorithms.

As a result of the above the public key is usually stored as a property on the key or as metadata in the application that uses the key. 

Can you share what algorithm your using?

**Comment by ruslan-gennadievich** [comment]
> Can you share what algorithm your using?
Im using ECDSA

You can also store the public key as it’s own object, CKO_PUBLIC_KEY, does your token have this object on it?
I have no public key object on token. I need get public key identifier for public key that consistent with the specified private key. According to http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html i can request CKA_PUBLIC_KEY_INFO (0x129) attribute.

> DER-encoding of the SubjectPublicKeyInfo for the associated public key (MAY be empty; **DEFAULT derived from the underlying private key data**; MAY be manually set for specific key types; if set; MUST be consistent with the underlying private key data)
> -

**Comment by rmhrisk** [comment]
`CKA_PUBLIC_KEY_INFO` will only be there if it was put there at generation or if the PKCS#11 implementation derives it and sets it. If it is not there this library can not return it.

**Comment by ruslan-gennadievich** [comment]
Yes, you are right. Thank your for help
I use SoftHSM, and as i see in https://github.com/opendnssec/SoftHSMv2/blob/f82d4eda55401a4d23e647d85a00a8b0c8ccf712/src/lib/P11Objects.cpp

> // TODO: CKA_PUBLIC_KEY_INFO is accepted, but we do not calculate it.

So, SoftHSM not auto calculate CKA_PUBLIC_KEY_INFO.

**Comment by rmhrisk** [comment]
This is common

**Comment by microshine** [comment]
You can use `CKA_PUBLIC_EXPONENT` and `CKA_MODULUS` to get public key data

![image](https://user-images.githubusercontent.com/7333669/100278356-c81db000-2f75-11eb-827b-5993bc41049f.png)

If you need to get public key in SPKI format you need to use any ASN.1 module for that (eg [asn1.js](https://github.com/PeculiarVentures/asn1.js), [@peculiar/asn1-rsa](https://github.com/PeculiarVentures/asn1-schema/tree/master/packages/rsa)) to encode that package manually
