### ISSUE TITLE
Async C_OpenSession/C_CloseSession, C_Login/C_Logout, C_Sign

### ISSUE THREAD

**Issue by indianscout** [PeculiarVentures/pkcs11js#49]
According the docs this library is sync only. Is there a way to use it async?
This would be very usefull for the following calls:
* C_OpenSession/C_CloseSession
* C_Login/C_Logout
* C_SignInit
* C_Sign
* C_DestroyObject

**Comment by rmhrisk** [comment]
No

**Comment by microshine** [comment]
`pkcs11js` supports callback functions for:
- C_Encrypt
- C_Decrypt
- C_Digest
- C_Sign
- C_Verify
- C_GenerateKey
- C_GenerateKeyPair
- C_WrapKey
- C_UnwrapKey
- C_DeriveKey

if you need to use asyn/await you need to wrap those functions. See [Converting callbacks to promises](https://zellwk.com/blog/converting-callbacks-to-promises/) article.

Other functions require module improvement. PR is appreciated.
