### ISSUE TITLE
How  to sign a string through Hardware token

### ISSUE THREAD

**Issue by fereydoun** [PeculiarVentures/pkcs11js#50]
by methods: C_SignInit, C_SignUpdate , C_Sign or C_SignFinal

**Comment by microshine** [comment]
Have you seen [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11/tree/master/src) module? It makes using PKCS#11 tokens easier

If you want to implement signing via `pkcs11js` module please show a code you are using and errors you have

You can take some examples from tests
  - [C_SignInit, C_Sign](https://github.com/PeculiarVentures/pkcs11js/blob/master/test/test.js#L277)
  - [C_SignInit, C_SignUpdate, C_SignFinal](https://github.com/PeculiarVentures/pkcs11js/blob/master/test/test.js#L297)

**Comment by fereydoun** [comment]
in this sample code i don't want generate key.
I want use usb hardware token certificate instead of generate key.

var publicKeyTemplate = [
    { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PUBLIC_KEY },
    { type: pkcs11js.CKA_TOKEN, value: false },
    { type: pkcs11js.CKA_LABEL, value: "My RSA Public Key" },
    { type: pkcs11js.CKA_PUBLIC_EXPONENT, value: new Buffer([1, 0, 1]) },
    { type: pkcs11js.CKA_MODULUS_BITS, value: 2048 },
    { type: pkcs11js.CKA_VERIFY, value: true }
];
var privateKeyTemplate = [
    { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PRIVATE_KEY },
    { type: pkcs11js.CKA_TOKEN, value: false },
    { type: pkcs11js.CKA_LABEL, value: "My RSA Private Key" },
    { type: pkcs11js.CKA_SIGN, value: true },
];
var keys = pkcs11.C_GenerateKeyPair(session, { mechanism: pkcs11js.CKM_RSA_PKCS_KEY_PAIR_GEN }, publicKeyTemplate, privateKeyTemplate);

pkcs11.C_SignInit(session, { mechanism: pkcs11js.CKM_SHA256_RSA_PKCS }, keys.privateKey);
pkcs11.C_SignUpdate(session, new Buffer("Incomming message 1"));
pkcs11.C_SignUpdate(session, new Buffer("Incomming message N"));
var signature = pkcs11.C_SignFinal(session, Buffer(256));

**Comment by microshine** [comment]
You need to get your private key from the token. You can do it by using `C_FindObjectsInit`, `C_FindObjects`, `C_FindObjectsFinal` functions.

If you want to put your private key to the token you can do it by using `C_GenerateKeyPair` function with enabled `CKA_TOKEN` attribute.

See [PKCS#11 documentation](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html)

**Comment by fatimazahra-hanounou** [comment]
Hi  fereydoun,

Please i have the same issue, did you found any solution??

Thank's

**Comment by fereydoun** [comment]
@fatimazahra-hanounou 
I used graphene:
https://www.npmjs.com/package/graphene-pk11


var mod = Module.load("driver file path", "SoftHSM");
try {
        mod.initialize();
        var slot = mod.getSlots(0);
        if (slot.flags & graphene.SlotFlag.TOKEN_PRESENT) {
            var session = slot.open();
            session.login("token password");
            var sign = session.createSign("SHA256_RSA_PKCS", session.find({class: graphene.ObjectClass.PRIVATE_KEY}).items(0));
            sign.update('data to sign');
            var signature = sign.final()
            session.logout();
        }
        else {
            console.error("Slot is not initialized");
        }

    }
    catch(e){
        console.error(e);
    }
    finally {
        mod.finalize();
    }
