### ISSUE TITLE
PKCS11JS: Error CKR_KEY_FUNCTION_NOT_PERMITTED:104 on  pkcs11.C_GenerateKeyPair 

### ISSUE THREAD

**Issue by fatimazahra-hanounou** [PeculiarVentures/pkcs11js#51]
Hi,

I'm using a certified usb device to sign documents.

This my code:

**************************************************************
var pkcs11js = require("./node_modules/pkcs11js");

var pkcs11 = new pkcs11js.PKCS11();
pkcs11.load("C:/Program Files/Gemalto/Classic Client/BIN/gclib.dll");

pkcs11.C_Initialize();

try {
    // Getting info about PKCS11 Module
    var module_info = pkcs11.C_GetInfo();
    console.log("Module: ");
    console.log(module_info);

    // Getting list of slots
    var slots = pkcs11.C_GetSlotList(true);
    var slot = slots[0];
    console.log("Slots: ");
    console.log(slots);

    // Getting info about slot
    var slot_info = pkcs11.C_GetSlotInfo(slot);
    console.log("Slot info: ");
    console.log(slot_info);
    // Getting info about token
    var token_info = pkcs11.C_GetTokenInfo(slot);

    // Getting info about Mechanism
    var mechs = pkcs11.C_GetMechanismList(slot);
    var mech_info = pkcs11.C_GetMechanismInfo(slot, mechs[0]);
    console.log("Mechanisme ");
    console.log(mech_info);

    var session = pkcs11.C_OpenSession(slot, pkcs11js.CKF_RW_SESSION | pkcs11js.CKF_SERIAL_SESSION);
    console.log("Session ");
    console.log(session);

    // Getting info about Session
    var info = pkcs11.C_GetSessionInfo(session);
    console.log("Session Info");
    console.log(info);

    pkcs11.C_Login(session, 1, "856489");

    console.log("Info");    
    console.log(pkcs11js.CKM_SHA256_RSA_PKCS);
    console.log("Info 2"); 
    console.log(pkcs11js.CKM_RSA_PKCS_KEY_PAIR_GEN);
    
    var publicKeyTemplate = [
        { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PUBLIC_KEY },
        { type: pkcs11js.CKA_TOKEN, value: false },
        { type: pkcs11js.CKA_LABEL, value: "My RSA Public Key" },
        { type: pkcs11js.CKA_PUBLIC_EXPONENT, value: Buffer.from([1, 0, 1]) },
        { type: pkcs11js.CKA_MODULUS_BITS, value: 2048 },
        { type: pkcs11js.CKA_VERIFY, value: true }
    ];

    console.log("Public Key");
    console.log(publicKeyTemplate);
    console.log(pkcs11js.CKO_PUBLIC_KEY);

    var privateKeyTemplate = [
        { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PRIVATE_KEY },
        { type: pkcs11js.CKA_TOKEN, value: false },
        { type: pkcs11js.CKA_LABEL, value: "My RSA Private Key" },
        { type: pkcs11js.CKA_SIGN, value: true },
    ];
    
    console.log("Private Key");
    console.log(privateKeyTemplate);
    console.log(pkcs11js.CKO_PRIVATE_KEY);

    var keys = pkcs11.C_GenerateKeyPair(session, { mechanism: pkcs11js.CKM_RSA_PKCS_KEY_PAIR_GEN }, publicKeyTemplate, privateKeyTemplate);

    console.log("Keys");
    console.log(keys);

    pkcs11.C_SignInit(session, { mechanism: pkcs11js.CKM_SHA256_RSA_PKCS },
        keys.privateKey); 

    pkcs11.C_SignUpdate(session, new Buffer("Incomming message 1"));
    pkcs11.C_SignUpdate(session, new Buffer("Incomming message N"));

    var signature = pkcs11.C_SignFinal(session, Buffer(256));

    pkcs11.C_Logout(session);
    pkcs11.C_CloseSession(session);
}
catch(e){
    console.error(e);
}
finally {
    pkcs11.C_Finalize();
}
**************************************************************************
When the program try to generate the keys "pkcs11.C_GenerateKeyPair", i get : " Error CKR_KEY_FUNCTION_NOT_PERMITTED:104".

Can you help me to resolve the problem ??

**Comment by rmhrisk** [comment]
It sounds like your token has been configured to be a read only token.

What kind of token is this?

**Comment by microshine** [comment]
From PKCS#11 specification
`
CKR_KEY_FUNCTION_NOT_PERMITTED: An attempt has been made to use a key for a cryptographic purpose that the key’s attributes are not set to allow it to do.  For example, to use a key for performing encryption, that key MUST have its CKA_ENCRYPT attribute set to CK_TRUE (the fact that the key MUST have a CKA_ENCRYPT attribute implies that the key cannot be a private key).  This return value has lower priority than CKR_KEY_TYPE_INCONSISTENT
`

**Comment by fatimazahra-hanounou** [comment]
Thank you for your answer,

I'm using a Class 3 Device: certificate on cryptographic support evaluated.
It includes a certificate allowing electronique signature (with a public and a private keys).

My issue is to allow the device owner to sign a pdf file ( the program should get the certificate and join it in the pdf ).

I'm new in this technologie, i use this link to get informations: 
(https://www.cryptsoft.com/pkcs11doc/v100/pkcs11__all_8h.html#aC_GenerateKeyPair)
but i'm not sure if i shall use GenerateKeyPair or FindObjects.

For GenerateKeyPair: if  pkcs11js.CKA_TOKEN= true, i get **Error: CKR_DEVICE_MEMORY:49**
and if it's  false i get " Error CKR_KEY_FUNCTION_NOT_PERMITTED:104 .

**Comment by rmhrisk** [comment]
Being level 3 doesn’t matter here.


Some devices won’t let you generate new keys, that’s a way they can be configured.

Your token is saying it’s not able to generate the key for you.

Can you tell us about the token and its  middleware?

**Comment by microshine** [comment]
You need to make the next steps

- Initialize a token (`C_Initialize`)
- Get slot list (`C_GetSlotList`)
- Open session for selected slot (`C_OpenSession`)
- Log in session, if required (`C_Login`)
- Find out a signing key (`C_FindObjectsInit`, `C_FindObjects`, `C_FindObjectsFinal`)
- Use the signing key to sign PDF document (`C_SignInit`, `C_Sign` or `C_SignInit`, `C_SignUpdate`, `C_SignFinal`)

**Comment by fatimazahra-hanounou** [comment]
> Being level 3 doesn’t matter here.
> 
> Some devices won’t let you generate new keys, that’s a way they can be configured.
> 
> Your token is saying it’s not able to generate the key for you.
> 
> Can you tell us about the token and its middleware?

Hi rmhrisk ,

Thank you for reply,

The Toke info:
****************************
Object {label: "GemP15-1", 
manufacturerID: "Gemalto S.A.", 
model: "Classic V3",
serialNumber: "38C000AB63242A76", 
flags: 1037, …}
*****************************

**Comment by fatimazahra-hanounou** [comment]
> You need to make the next steps
> 
> * Initialize a token (`C_Initialize`)
> * Get slot list (`C_GetSlotList`)
> * Open session for selected slot (`C_OpenSession`)
> * Log in session, if required (`C_Login`)
> * Find out a signing key (`C_FindObjectsInit`, `C_FindObjects`, `C_FindObjectsFinal`)
> * Use the signing key to sign PDF document (`C_SignInit`, `C_Sign` or `C_SignInit`, `C_SignUpdate`, `C_SignFinal`)

Hi  microshine,

Thak  you,

I followed the same steps => now i don't have any error message, but i'm not sure if i'm in the correct way.
I used the SignUpdate methode to sign "text" as bellow:
    *pkcs11.C_SignUpdate(session, Buffer.from("Incomming message 1"));
    *pkcs11.C_SignUpdate(session, Buffer.from("Incomming message N"));

Now shall i give the pdf instead of text ?? and than generate a new pdf with signature ( if yes how can do that)??

I'm so sorry for the abuse.

**Comment by fatimazahra-hanounou** [comment]
Hi,

Could you help me, to know how can i generate X509 Certificate from my USB token?

I used the code bellow, but it return null value:

//*****************************************
    pkcs11.C_FindObjectsInit(session, [
        { type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_CERTIFICATE },
        { type: pkcs11js.CKA_TOKEN, value: true },
        { type: pkcs11js.CKA_CERTIFICATE_TYPE, value: pkcs11.CKC_X_509 }
    ]);

    var hObject = pkcs11.C_FindObjects(session);
    console.log("hObject certificate avant while")
    console.log(hObject);
    while (hObject) {
        var attrs = pkcs11.C_GetAttributeValue(session, hObject, [
            { type: pkcs11js.CKA_CLASS , value: pkcs11js.CKO_CERTIFICATE },
            { type: pkcs11js.CKA_TOKEN , value: true },
            { type: pkcs11js.CKA_CERTIFICATE_TYPE, value: pkcs11.CKC_X_509 }
        ]);

        keys1.certifcate = hObject;

        hObject = pkcs11.C_FindObjects(session);
    }
    console.log(keys1.certifcate); //Return Null

    pkcs11.C_FindObjectsFinal(session);
//*****************************************

**Comment by microshine** [comment]
I'd like to suggest you use other our modules

- [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11)
   It implements WebCrypto API and supports KeyStorage and CertStorage. You can use that module for Certificate, PrivateKey, PublicKey, and CSR
- [Fortify](https://fortifyapp.com/)
   It implements the same API and allows to use PKCS#11 libraries in browsers
- [@peculiar/x509](https://github.com/PeculiarVentures/x509)
   If you need additional functions for CSR generation, Certificate chain builder, Certificate parser, use it

See `@peculiar/x509` readme file for certificate creation examples
