### ISSUE TITLE
How to read and generate X.509 certificate stored on usb token in js

### ISSUE THREAD

**Issue by dpccrt87** [PeculiarVentures/pkcs11js#53]
Hi Experts,
I am using Gemalto usb token for my Javascript application. I am accessing token's functionality through PKCS11 Javascript library.

I've been able to: Generate public and private key, encrypt/decrypt, sign/verify.

But the main problem is: 
How can i read attributes of certificate stored inside the token using Javascript code?, so that I can move on to the next step, which will be the signature of the pdf document via this certificate (always using javascript).

I thoroughly looked through the PKCS#11 documentation, and over the Internet, but I couldn't find answer to my question.

I would appreciate any hints to solve this problem. 
Thanks for help.

**Comment by rmhrisk** [comment]
Are you going to do this in the browser? If so I recommend using FortifyApp.com.

if not we you can look at its source as it does this.

Happy to provide more info, I just suspect Fortify is the right solution.

**Comment by dpccrt87** [comment]
Hi rmhrisk,
Thank you for reply.
Yes i will do it in the browser.

**Comment by rmhrisk** [comment]
Take a look at Fortify, that’s what you want.
