### ISSUE TITLE
PKCS11.C_Sign on Ubuntu failed with Segmentation fault (core dumped) for nodejs 8.16.0.

### ISSUE THREAD

**Issue by feliciss** [PeculiarVentures/pkcs11js#55]
Source code:

```javascript
const sig = pkcs11.C_Sign(pkcs11Session, digest,
				Buffer.alloc(this._keySize));
```

The digest is 'Hello World!' with buffer.from parse.

Node version: 8.16.0.
Platform: Ubuntu.
Function call: pkcs11.C_Sign().
Error msg: Segmentation fault (core dumped).
Package version: pkcs11js@1.0.6.

I have tried the newest pkcs11js version and it didn't work anyway.

**Comment by rmhrisk** [comment]
The core dump is likely in the PKCS#11 library, what library, what does its logs say happened before?

**Comment by microshine** [comment]
We've got successful tests for `C_Sign` functions on [CircleCI](https://travis-ci.org/PeculiarVentures/pkcs11js/jobs/585442098#L1716)

### CircleCI System
```
OS: Ubuntu 16.04.6 LTS
NodeJS: v8.16.1
pkcs11js: 1.0.19
PKCS#11: SoftHSMv2
```

**Comment by 5sWind** [comment]
> We've got successful tests for `C_Sign` function on [CircleCI](https://travis-ci.org/PeculiarVentures/pkcs11js/jobs/585442098#L1716)
> 
> ### CircleCI System
> ```
> OS: Ubuntu 16.04.6 LTS
> NodeJS: v8.16.1
> pkcs11js: 1.0.19
> PKCS#11: SoftHSMv2
> ```

Sorry I forgot to mention that I am using Ubuntu 18.04...

**Comment by 5sWind** [comment]
And the openssl version is 1.1.1 (the latest version).

**Comment by microshine** [comment]
I can reproduce this exception locally. I'll fix this problem

**Comment by microshine** [comment]
What PKCS#11 library do you use? 

Looks like we had got a Segmentation fault before
https://github.com/PeculiarVentures/pkcs11js/issues/47

Here is an output of the segmentation fault stack trace
```
Error: signal 11:
  /home/vsts/work/1/s/pkcs11js/build/Debug/pkcs11.node(_Z7handleri+0x34) [0x7f9eca93c57e]
  /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f9eccbf34b0]
  node(RSA_blinding_on+0x130) [0x126d560]
  /usr/local/lib/softhsm/libsofthsm2.so(+0x7a2b1) [0x7f9eca6a82b1]
  /usr/local/lib/softhsm/libsofthsm2.so(+0x36f2c) [0x7f9eca664f2c]
  /usr/local/lib/softhsm/libsofthsm2.so(C_Sign+0x33) [0x7f9eca6470e3]
  /home/vsts/work/1/s/pkcs11js/build/Debug/pkcs11.node(+0x7024f) [0x7f9eca96824f]
  /home/vsts/work/1/s/pkcs11js/build/Debug/pkcs11.node(_ZN6PKCS116C_SignEmSt10shared_ptrINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES7_+0x80) [0x7f9eca96abbc]
  /home/vsts/work/1/s/pkcs11js/build/Debug/pkcs11.node(_ZN7WPKCS116C_SignERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE+0x67a) [0x7f9eca98b0ae]
  /home/vsts/work/1/s/pkcs11js/build/Debug/pkcs11.node(+0x80274) [0x7f9eca978274]
  node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x193) [0xa99113]
  node() [0xb1033c]
  node(_ZN2v88internal21Builtin_HandleApiCallEiPPNS0_6ObjectEPNS0_7IsolateE+0xaf) [0xb10f8f]
  [0x1638b9842fd]
```

Maybe it's SoftHSM exception. But we need to double-check using another PKCS#11 library.

@5sWind Can you try NSS library with pkcs11js?
