### ISSUE TITLE
Is it possible to access pkcs11 interface from webapp?

### ISSUE THREAD

**Issue by MasakiMinamide** [PeculiarVentures/pkcs11js#58]
Hi. 
I'm currently making a webapp with React, and I would like users to be able to use their smartcard to authenticate their id. 

Using pkcs11-tool on command line worked perfect with my smartcard. Now how can I integrate it with my webapp? Is this the right package? I'm kind of lost...

**Comment by rmhrisk** [comment]
No, take a look at FortifyApp.com

**Comment by MasakiMinamide** [comment]
Oh that looks more of what I would like to use. Thanks!
