### ISSUE TITLE
Can I use this lib to get private key and Certificate from HSM ?

### ISSUE THREAD

**Issue by Arsira-star** [PeculiarVentures/pkcs11js#61]
I have Lunaclient that install in my server and it register to connet to HSM.
In HSM has Certificate PrivateKey and PublicKey
How can I get one of that to make sign

**Comment by rmhrisk** [comment]
Yes this library provides a binding for PKCS11 that you can use with the Luna client. 

Using this library means you intend to use PKCS11 directly and therefor the path forward is for you to find a sample in the Luna documentation that describes the call pattern you want in another language and recreate it using pkcs11js.

We’re happy to help with library specific questions.

You may want to look at the higher level library Graphene, this is a simpler API to use in many cases.

**Comment by microshine** [comment]
I'd like to suggest you use other our modules

- [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11)
   It implements WebCrypto API and supports KeyStorage and CertStorage. You can use that module for Certificate, PrivateKey, PublicKey, and CSR
- [Fortify](https://fortifyapp.com/)
   It implements the same API and allows to use PKCS#11 libraries in browsers
- [@peculiar/x509](https://github.com/PeculiarVentures/x509)
   If you need additional functions for CSR generation, Certificate chain builder, Certificate parser, use it
