### ISSUE TITLE
how can get this path /usr/local/lib/softhsm/libsofthsm2.so in windows 

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/pkcs11js#66]
how can use this package with win10

**Comment by microshine** [comment]
- Install SoftHSM on Windows (eg [SoftHSM2 for Windows](https://github.com/disig/SoftHSM2-for-Windows))
- Change '/usr/local/lib/softhsm/libsofthsm2.so' path to Windows softhsm library location

**Comment by abdalahshaban** [comment]
can not found this file libsofthsm2.so in C:\SoftHSM2\lib

**Comment by microshine** [comment]
please share a list of SoftHSM files

**Comment by abdalahshaban** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/20366073/98945644-74ce4b00-24fb-11eb-987e-29741bfb6df3.png)

**Comment by abdalahshaban** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/20366073/98945712-8d3e6580-24fb-11eb-953b-30b692a00850.png)

**Comment by microshine** [comment]
Use `softhsm2-x64.dll`

**Comment by abdalahshaban** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/20366073/98956185-66d2f700-2508-11eb-8d5c-775156861b77.png)

**Comment by rmhrisk** [comment]
Is your issue solved?
