### ISSUE TITLE
it possible to use this package with angular 

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/pkcs11js#67]
it possible to use this package with angular

**Comment by rmhrisk** [comment]
It is intended for nodejs use cases, look at FortifyApp.com for browser use cases.

**Comment by abdalahshaban** [comment]
how can use this kind of auth in mean stack (angular , express js)

**Comment by abdalahshaban** [comment]
which package can i use in angular to work with hard token  instated FortifyApp.com  if can

**Comment by donskov** [comment]
Hi @abdalahshaban.

You can use one of:
1. Our web-component - https://fortifyapp.com/docs/installation/web-component.
2. Wrapper from web-component - https://www.npmjs.com/package/@peculiar/fortify-client-core.
3. Core library - https://www.npmjs.com/package/@webcrypto-local/client (examples https://peculiarventures.github.io/fortify-examples/).

Each of them works with the Fortify app.
