### ISSUE TITLE
get public key

### ISSUE THREAD

**Issue by abdalahshaban** [PeculiarVentures/pkcs11js#69]
get public key

**Comment by microshine** [comment]
What does it mean?

**Comment by microshine** [comment]
See our other modules. They allow getting a public key from the token in known formats.

- [graphene-pk11](https://github.com/PeculiarVentures/graphene)
- [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11)
- [Fortify](https://fortifyapp.com/)
