### ISSUE TITLE
I want to install pkcs11js but I have not managed to run it

### ISSUE THREAD

**Issue by sheko016** [PeculiarVentures/pkcs11js#76]
Good afternoon team.
This is to notify that I want to install PKCS11JS in my laravel project, but I have not been able to achieve it, I get the following error.
ERROR in ./node_modules/pkcs11js/build/Release/pkcs11.node 1: 0
Module parse failed: Unexpected character '(1: 0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

could you please help me
Greetings.

**Comment by sheko016** [comment]
Hello team, @rmhrisk @microshine  good afternoon, how are you doing?

I am going to explain my case a little.

I have a project in laravel that works 100%, we are currently making electronic signatures of PDF with .pfx files, which is where the electronic signature of each user is saved.
Even there I am perfect, it works 100%.

what happens now.
Electronic signatures are now coming in TOKEN USB Level 3

What is the detail that I have that I cannot communicate with the TOKEN USB device to be able to sign these PDFs.

So the server where the application with laravel is hosted is in Canada, and the users with the TOKEN USB are in Chile.

With PKCS11JS I can communicate from my server that is in Canada with the PCs of the users that are in Chile to be able to read the TOKEN USB device and then be able to sign the PDF with said electronic signature saved in the TOKEN USB.?

Waiting for your valuable reply, I say goodbye.

Greetings.

**Comment by rmhrisk** [comment]
Have you seen fortifyapp.com?

**Comment by sheko016** [comment]
no sir
I have not seen it.
but thanks for the recommendation
I'm going to read about https://fortifyapp.com/
Thank you again.
Greetings.
