### ISSUE TITLE
key pair not persistet as file object

### ISSUE THREAD

**Issue by akafazov** [PeculiarVentures/pkcs11js#77]
After some experimenting, I noticed that generated key pair is not persistet as a file in the tokens dir. Searching for objects finds the pair if it is generated within the same session, but not otherwise. I am also listing objects created by other PKCS11 tools. I am using SoftHSM2. Am I doing something wrong, maybe configuration wise?

```
        // generate EC key pair
        const privateKeyTemplate = [
            // { type: pkcs11js.CKA_ID,        value: ski },
            {type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PRIVATE_KEY},
            {type: pkcs11js.CKA_KEY_TYPE, value: pkcs11js.CKK_EC},
            {type: pkcs11js.CKA_PRIVATE, value: this._pkcs11Login},
            {type: pkcs11js.CKA_TOKEN, value: this._pkcs11Login && pkcs11Token},
            {type: pkcs11js.CKA_SIGN, value: true},
            {type: pkcs11js.CKA_DERIVE, value: true}
        ];
        const _pkcs11ParamsSizeToOid = {256: '06082A8648CE3D030107', 384: '06052B81040022'};
        const publicKeyTemplate = [
            // { type: pkcs11js.CKA_ID,        value: ski },
            {type: pkcs11js.CKA_CLASS, value: pkcs11js.CKO_PUBLIC_KEY},
            {type: pkcs11js.CKA_KEY_TYPE, value: pkcs11js.CKK_EC},
            {type: pkcs11js.CKA_PRIVATE, value: false},
            {type: pkcs11js.CKA_TOKEN, value: this._pkcs11Login && pkcs11Token},
            {type: pkcs11js.CKA_VERIFY, value: true},
            {
                type: pkcs11js.CKA_EC_PARAMS,
                value: Buffer.from(_pkcs11ParamsSizeToOid[256], 'hex')
            }
        ];
        var keys = pkcs11.C_GenerateKeyPair(session, { mechanism: pkcs11js.CKM_EC_KEY_PAIR_GEN }, publicKeyTemplate, privateKeyTemplate);
        console.log("keys generated: %s", keys);
```

**Comment by microshine** [comment]
@akafazov Have you seen [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11). That module is based on `pkcs11js` and allows to work with RSA, EC, SHA, and AES mechanisms easier

API allows to add keys to the token using generation params or KeyStorage object

**Comment by akafazov** [comment]
Hi @microshine,
Isn't the keypair automatically persisted by the SoftHSM2 on file when created. 


```
$ cat /etc/softhsm2.conf
# SoftHSM v2 configuration file

directories.tokendir = /webapp/tokens
objectstore.backend = file

# ERROR, WARNING, INFO, DEBUG
log.level = DEBUG

# If CKF_REMOVABLE_DEVICE flag should be set
slots.removable = false

```

**Comment by akafazov** [comment]
I now see the object functions. Closing this issue.

**Comment by akafazov** [comment]
Actually objects are created, but not persisted.

**Comment by microshine** [comment]
`CKA_TOKEN` attribute must manage that case when the key must be stored. I've never tried to find out the key file in SoftHSM. But when I create the key with `CKA_TOKEN` attribute I can use that key later.

**Comment by microshine** [comment]
Try to use `CKA_SENSITIVE`. I use it in `node-webcrypto-p11`
https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/mechs/ec/crypto.ts#L30

**Comment by akafazov** [comment]
CKA_TOKEN did the trick.
