### ISSUE TITLE
unable to install pkcs11.js in windows 10

### ISSUE THREAD

**Issue by avinashuttav** [PeculiarVentures/pkcs11js#79]
when we try to install pkcs11.js in windows system, we are facing below issue currently.
npm install -g pkcs11js

> pkcs11js@1.2.3 install C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js
> node-gyp rebuild

C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  main.cpp
  dl.cpp
  const.cpp
  error.cpp
  v8_convert.cpp
  template.cpp
  mech.cpp
  param.cpp
  param_aes.cpp
  param_rsa.cpp
  param_ecdh.cpp
  pkcs11.cpp
  async.cpp
  node.cpp
  win_delay_load_hook.cc
C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js\src\pkcs11\pkcs11.cpp(131,14): error C2065: 'RTLD_NOW': undeclared identifier [C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js\build\pkcs11.vcx
proj]
C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js\src\pkcs11\pkcs11.cpp(131,25): error C2065: 'RTLD_LOCAL': undeclared identifier [C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js\build\pkcs11.v 
cxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\auttav\AppData\Roaming\npm\node_modules\pkcs11js
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pkcs11js@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pkcs11js@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\auttav\AppData\Roaming\npm-cache\_logs\2021-05-18T07_21_00_522Z-debug.log

**Comment by microshine** [comment]
Please try the latest version. I published the new version today `v1.2.4`

**Comment by avinashuttav** [comment]
yes, it works fine now.
Thank you
