### ISSUE TITLE
Meaning of variable name `token` in tests?

### ISSUE THREAD

**Issue by pinheadmz** [PeculiarVentures/pkcs11js#86]
In `test/test.js` you have:

```
      token = new pkcs11.PKCS11();
      token.load(softHsmLib);
      token.C_Initialize();
...
      const slots = token.C_GetSlotList();
... (etc)
```

I am just learning about the protocol and this confused me because according to https://www.cryptsoft.com/pkcs11doc/v230/ :

```
Slot | A logical reader that potentially contains a token.
Token | The logical view of a cryptographic device defined by Cryptoki.
```

...so my understanding is that "slots contain tokens" but the code in the test seems to imply that "tokens contain slots" ?

**Comment by rmhrisk** [comment]
Tokens contain slots

**Comment by pinheadmz** [comment]
I appreciate the answer but am still confused:

https://www.cryptsoft.com/pkcs11doc/v230/

> Cryptoki provides an interface to one or more cryptographic devices that are active in the system through a number of "slots". Each slot, which corresponds to a physical reader or other device interface, may contain a token. A token is typically "present in the slot" when a cryptographic device is present in the reader. Of course, since Cryptoki provides a logical view of slots and tokens, there may be other physical interpretations. It is possible that multiple slots may share the same physical reader. The point is that a system has some number of slots, and applications can connect to tokens in any or all of those slots.

**Comment by rmhrisk** [comment]
cryptographic device = PKCS11 token in a HSM like device

smart card = PKCS11 token 

USB toke  = PKCS11 token

Each of the above have "slots". 

Each slot, contains a logical or physical cryptographic implementation.

Generally you can think of a slot as a security domain (slot1 is accessible by app1)
