### ISSUE TITLE
RSA encryption/decryption support

### ISSUE THREAD

**Issue by luiszunigacr** [PeculiarVentures/pkcs11js#9]
I'd like to verify that this module supports RSA encryption with public key. 
There is an example in the README.md for signing/verifying, but how could I encrypt/decrypt with some RSA mechanism?

**Comment by rmhrisk** [comment]
pkcs11js is just pkcs#11 binding for node, you can look at any PKCS#11 example for encryption and map it to pkcs11js.

I suspect you would be better off by using graphene though which provides a higher level API. Check out the graphene-cli for an example of using it for encryption.
